module I18n exposing (I18n, en, pl)

{-| This file was generated by elm-i18n version 2.3.1.


-}


type alias I18n =
    { beatenHighScore : String
    , congratulations : String
    , gameHighScore : String -> String
    , gameOver : String
    , gameScore : String -> String
    , newHighScore : String -> String
    , playAgainBtn : String
    , thanksForPlaying : String
    , viewSource : String
    }


{-| `I18n` instance containing all values for the language En


-}
en : I18n
en =
    { beatenHighScore = "You beat my high score."
    , congratulations = "Congratulations!"
    , gameHighScore = \score_ -> "High score: " ++ score_
    , gameOver = "Game over"
    , gameScore = \score_ -> "Score: " ++ score_
    , newHighScore = \score_ -> "New high score! " ++ score_
    , playAgainBtn = "Play again?"
    , thanksForPlaying = "Thanks for playing!"
    , viewSource = "View source code ↗"
    }


{-| `I18n` instance containing all values for the language Pl


-}
pl : I18n
pl =
    { beatenHighScore = "Pobiłeś mój rekord."
    , congratulations = "Gratulacje!"
    , gameHighScore = \score_ -> "Najlepszy wynik: " ++ score_
    , gameOver = "Koniec gry"
    , gameScore = \score_ -> "Wynik: " ++ score_
    , newHighScore = \score_ -> "Nowy rekord! " ++ score_
    , playAgainBtn = "Jeszcze raz?"
    , thanksForPlaying = "Dzięki za grę!"
    , viewSource = "Zobacz kod źródłowy ↗"
    }
